name: Deploy Module

on:
    workflow_dispatch:


jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '16'

            - name: Install dependencies
              run: npm install

            - name: Get version from module.json
              id: get_version
              run: echo "VERSION=$(jq -r '.version' module.json)" >> $GITHUB_ENV
            
            - name: Build the project (Production)
              run: npm run build

            - name: Generate Changelog
              id: generate_changelog
              run: |
                LAST_TAG=$(git describe --tags --abbrev=0)
                echo "Last tag: $LAST_TAG"
                echo "Generating changelog since $LAST_TAG"
                git log "$LAST_LOG"..HEAD --pretty=format:"%s" > changelog.txt
                echo "Changelog content:"
                cat changelog.txt
            
            - name: Package the module
              run: zip -r spc-factory.zip dist/ module.json README.md

            - name: Create GitHub Release
              id: create_release
              uses: actions/create-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag_name: ${{ env.VERSION }}
                release_name: Release v${{ env.VERSION }}
                body_path: changelog.txt
                draft: false
                prerelease: true
            
            - name: Upload Release Asset (ZIP)
              uses: actions/upload-release-asset@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                upload_url: ${{ steps.create_release.outputs.upload_url }}
                asset_path: ./spc-factory.zip
                asset_name: spc-factory.zip
                asset_content_type: application/zip
            
            - name: Upload Release Asset (module.json)
              uses: actions/upload-release-asset@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                upload_url: ${{ steps.create_release.outputs.upload_url }}
                asset_path: ./module.json
                asset_name: module.json
                asset_content_type: application/json